export default {
  dropMarker: require("../assets/images/drop-marker.png"),
  pickupMarker: require("../assets/images/pickup-marker.png"),
  liveLocationBtn: require("../assets/images/greenIndicator.png"),
  bike: require("../assets/images/bike.png"),
  bolero: require("../assets/images/bolero.png"),
  cash: require("../assets/images/cash.png"),
  discount: require("../assets/images/discount.png"),
  truck: require("../assets/images/truck.png"),
  duty: require("../assets/images/duty.png"),
  arrowRight: require("../assets/images/arrow-left.png"),
  arrowLeft: require("../assets/images/arrow-right.png"),
  docReview: require("../assets/images/docReview.jpg"),
  locationAccess: require("../assets/images/locationAccess.png"),
  noDataFound: require("../assets/images/empty-box.png"),
  tataAce: require("../assets/images/tata-ace.png"),
};
